### ISSUE TITLE
Oriana crasg with cast R

### ISSUE THREAD

**Issue by isgood72** [memsenpai/Ensoulsharp.Sayuto#6]
Exception occured! EnsoulSharp might crash!

Type: System.Exception
Message: Could not find child with name katarinae

Stracktrace:
   at EnsoulSharp.SDK.MenuUI.Menu.GetValue[T](String name)
   at DaoHungAIO.Champions.Orianna.AIBaseClientProcessSpellCast(AIBaseClient sender, AIBaseClientProcessSpellCastEventArgs args)
   at EnsoulSharp.AIBaseClient.?????????????????????????????????????????(?????????????????????????????????????????* , ?????????????????????????????????????????* )
========================================

**Comment by isgood72** [comment]
========================================
Exception occured! EnsoulSharp might crash!

Type: System.Exception
Message: Could not find child with name dianateleport

Stracktrace:
   at EnsoulSharp.SDK.MenuUI.Menu.GetValue[T](String name)
   at DaoHungAIO.Champions.Orianna.AIBaseClientProcessSpellCast(AIBaseClient sender, AIBaseClientProcessSpellCastEventArgs args)
   at EnsoulSharp.AIBaseClient.?????????????????????????????????????????(?????????????????????????????????????????* , ?????????????????????????????????????????* )
========================================
